### ISSUE TITLE
error TS2304: Cannot find name 'HeadersInit'.

### ISSUE THREAD

**Issue by GabrielGab** [sholladay/pogo#25] opened 2020-05-08 19:59 UTC
Hi there , 
 While deno 1.0.0 compiling, I got this error in recent days, 

error TS2304: Cannot find name 'HeadersInit'.
► https://deno.land/x/pogo/lib/response.ts:7:15
7     headers?: HeadersInit,
                ~~~~~~~~~~~
Thanks in advance , great expectations on deno and new libraries

**Comment by sholladay** [comment] 2020-05-09 01:21
Hmm can you double check your Deno version? It should work on recent versions of Deno.

**Comment by sholladay** [comment] 2020-05-09 01:28
Duplicate of #23

**Comment by GabrielGab** [comment] 2020-05-09 23:43
Trying on version rc2 and is working fine !.
Hoping stability and reliability will arrive soon !

**Comment by sholladay** [comment] 2020-05-10 19:54
Just updated Pogo's dependencies and CI is testing Deno 0.42.0, but the 1.0.0 release candidates should work too. Let me know if you have any other issues.

**Closed by sholladay** 2020-05-10 19:54 UTC
